@DigitalOnboarding.Server_HostAddress = http://localhost:5274

GET {{DigitalOnboarding.Server_HostAddress}}/weatherforecast/
Accept: application/json
###

GET {{DigitalOnboarding.Server_HostAddress}}/projects/
Accept: application/json
###

GET {{DigitalOnboarding.Server_HostAddress}}/projects/1
Accept: application/json
###